### ISSUE TITLE
[Feature]: Support for multiple datastore for storing expectations and validation results.

### ISSUE THREAD

**Issue by subham611** [Swiple/swiple#69]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://swiple.io) and [the FAQ's](https://swiple.io/docs/faq) and still think this is a bug
- [X] I am confident that the issue is with swiple and not my configuration in `docker/.env` or `docker/.env-non-dev`

### Description

Need a feature to change expectation and validation store to GCS/BQ in swiple? I want to store my expectation in GCS and validation result in BQ. Feature should support different datastore for expectation and validation results.
slack link: https://swiple.slack.com/archives/C03U46W8L9L/p1673418448418559

**Comment by KentonParton** [comment]
Hey @subham611 ! Apologies for the very delayed response! Something we would be happy to support is a hook based approach where you could tie in to certain events but Swiple would not read from these sources. If we did add support for additional data sources, it would become very challenging to maintain.
